### ISSUE TITLE
Questions regarding the "mispronounced" field in score.json

### ISSUE THREAD

**Issue by teinhonglo** [jimbozhang/speechocean762#10]
Hi,

I have a few questions regarding the "mispronounced" field in the score.json file:

1. What do the abbreviations IR, AR, TR, DZ, TS, and DR (These phones are not shown in the cmu dictionary) stand for?
2. What does the special token * represent? Does it indicate an accent?
3. Is there any documentation available for reference?

Thank you!
Tien-Hong

**Comment by jimbozhang** [comment]
@teinhonglo Thank you for your questions.

For your question1, we apologize for this. We will soon update the field to use all phones in the CMU dictionary.

For your question 2 and 3, I have just updated the README.md and provided a more detailed introduction: https://github.com/jimbozhang/speechocean762?tab=readme-ov-file#the-mispronunciations-block

**Comment by jimbozhang** [comment]
Fixed in https://github.com/jimbozhang/speechocean762/pull/13

**Comment by a2d8a4v** [comment]
Hi, @jimbozhang 
Can you also help update the annotations on Hugginface?

[https://huggingface.co/datasets/mispeech/speechocean762](https://huggingface.co/datasets/mispeech/speechocean762)

Thank you for your attention!

**Comment by jimbozhang** [comment]
@a2d8a4v Sorry for the long delay. The HuggingFace dataset has been updated with the latest annotations from this repo, including the mispronunciations field.

https://huggingface.co/datasets/mispeech/speechocean762
