### ISSUE TITLE
What's the meaning of * in pronounced-phone when having mispronunciations?

### ISSUE THREAD

**Issue by tangYang7** [jimbozhang/speechocean762#11]
Hello, First of all, thank you for developing this corpus. 

I noticed that there are new labels in `score.json` and have some question since there are no directions to answer it. I'm wondering what is * after a phone in pronounced-phone, such as **T***, **AH***, or **R*** below the following example. 

Thank you very much for your time and assistance!

Best regards.

```
"000480033": {
    "accuracy": 5,
    "completeness": 10,
    "fluency": 7,
    "prosodic": 7,
    "text": "ZERO FIVE EIGHT THREE",
    "total": 5,
    "words": [
...
      {
        "accuracy": 3,
        "mispronunciations": [
          {
            "canonical-phone": "TH",
            "index": 0,
            "pronounced-phone": "S"
          },
          {
            "canonical-phone": "R",
            "index": 1,
            "pronounced-phone": "R*"
          }
        ],
        "phones": [
          "TH",
          "R",
          "IY0"
        ],
        "phones-accuracy": [
          0.2,
          0.4,
          1.6
        ],
        "stress": 10,
        "text": "THREE",
        "total": 4
      }
    ]
  },
  ```

**Comment by jimbozhang** [comment]
Thank you for pointing out the misinformation. I have just updated the README.md and provided a more detailed introduction: https://github.com/jimbozhang/speechocean762?tab=readme-ov-file#the-mispronunciations-block
